name: "Infrastructure Penetration Test"
description: "Complete infrastructure security assessment pipeline"
author: "PADOCCA Team"
version: "1.0"

settings:
  cache:
    enabled: true
    ttl: 7200  # 2 hours for infrastructure
  
  stealth:
    enabled: true
    delay_min: 2000
    delay_max: 8000
    randomize_user_agents: false  # Not needed for infra
  
  parallel:
    max_workers: 50  # More workers for port scanning
    rate_limit: 20
  
  output:
    format: "json"
    directory: "./results/infra"

stages:
  # Stage 1: Network Discovery
  - name: "network_discovery"
    description: "Discover network topology and hosts"
    parallel: false
    steps:
      - module: "network_discovery"
        config:
          targets: "{{target}}"
          techniques: ["arp", "icmp", "tcp"]
          
      - module: "subdiscovery"
        config:
          domain: "{{target}}"
          sources: ["zonetransfer", "bruteforce", "alterations"]
          validate: true
          ports: true
          output: "{{output.directory}}/hosts.json"

  # Stage 2: Port Scanning
  - name: "port_scanning"
    description: "Comprehensive port and service scanning"
    parallel: true
    depends_on: ["network_discovery"]
    steps:
      - module: "portscan"
        config:
          targets: "{{network_discovery.subdiscovery.active_subdomains}}"
          ports: "1-65535"  # Full port scan
          techniques: ["syn", "ack", "udp"]
          service_detection: true
          os_detection: true
          aggressive: false
          
      - module: "service_enum"
        config:
          targets: "{{network_discovery.subdiscovery.active_subdomains}}"
          deep_scan: true

  # Stage 3: Service Analysis
  - name: "service_analysis"
    description: "Detailed analysis of discovered services"
    parallel: true
    depends_on: ["port_scanning"]
    steps:
      - module: "ssl_analysis"
        config:
          targets: "{{port_scanning.portscan.ssl_services}}"
          deep_scan: true
          check_vulnerabilities: true
          
      - module: "smb_enum"
        config:
          targets: "{{port_scanning.portscan.smb_services}}"
          enumerate_shares: true
          enumerate_users: true
          
      - module: "database_enum"
        config:
          targets: "{{port_scanning.portscan.database_services}}"
          check_default_creds: true

  # Stage 4: Vulnerability Assessment
  - name: "vulnerability_assessment"
    description: "Identify vulnerabilities in infrastructure"
    parallel: true
    depends_on: ["service_analysis"]
    steps:
      - module: "template_scan"
        config:
          targets: "{{network_discovery.subdiscovery.active_subdomains}}"
          templates: "./templates/infrastructure/**/*.yaml"
          tags: ["cve", "misconfig", "default-login", "exposure"]
          severity: ["critical", "high"]
          
      - module: "compliance_check"
        config:
          targets: "{{network_discovery.subdiscovery.active_subdomains}}"
          standards: ["cis", "pci-dss", "hipaa"]

  # Stage 5: Privilege Escalation
  - name: "privilege_escalation"
    description: "Test for privilege escalation paths"
    parallel: false
    depends_on: ["vulnerability_assessment"]
    manual_approval: true
    steps:
      - module: "credential_testing"
        config:
          vulnerabilities: "{{vulnerability_assessment.template_scan.auth_vulns}}"
          test_lateral_movement: true
          
      - module: "exploit_chains"
        config:
          vulnerabilities: "{{vulnerability_assessment.template_scan.exploitable}}"
          chain_exploits: true
          safe_mode: true

  # Stage 6: Reporting
  - name: "reporting"
    description: "Generate infrastructure assessment report"
    depends_on: ["privilege_escalation"]
    steps:
      - module: "report_generator"
        config:
          type: "infrastructure"
          format: ["html", "pdf", "excel"]
          include_remediation: true
          risk_matrix: true
          executive_summary: true
          output: "{{output.directory}}/infra_report"

conditions:
  - if: "{{port_scanning.portscan.open_ports contains 445}}"
    then:
      - module: "eternal_blue_check"
        config:
          safe_check: true
          
  - if: "{{port_scanning.portscan.open_ports contains 3389}}"
    then:
      - module: "bluekeep_check"
        config:
          safe_check: true

on_error:
  - action: "log"
    level: "error"
  - action: "save_partial_results"
  - action: "continue"

on_success:
  - action: "generate_attack_graph"
  - action: "archive_results"
  - action: "notify"
    message: "Infrastructure assessment completed"
