name: "Stealth Web Pentest"
description: "Advanced stealth mode web penetration testing pipeline"
author: "PADOCCA Security Team"
version: "1.0.1"

settings:
  cache:
    enabled: true
    ttl: 7200
  stealth:
    enabled: true
    level: 3
    delay_min: 2000
    delay_max: 8000
    randomize_user_agents: true
  parallel:
    max_workers: 2
    rate_limit: 10
  output:
    format: "json"
    directory: "./results/stealth_scan"

stages:
  - name: "passive_recon"
    description: "Passive information gathering"
    parallel: false
    steps:
      - module: "subdiscovery"
        config:
          target: "{{.target}}"
          passive_only: true
          sources:
            - "crtsh"
            - "wayback"
            - "alienvault"

  - name: "slow_scan"
    description: "Slow port scanning"
    depends_on:
      - "passive_recon"
    parallel: false
    steps:
      - module: "portscan"
        config:
          scan_type: "stealth_syn"
          timing: "paranoid"
          ports: "80,443,8080,8443"

  - name: "vuln_scan"
    description: "Vulnerability scanning"
    depends_on:
      - "slow_scan"
    parallel: false
    steps:
      - module: "template_scan"
        config:
          adaptive_timing: true
          max_requests_per_host: 50

on_error:
  - action: "log"
    level: "debug"
  - action: "pause"
    duration: 60

on_success:
  - action: "secure_archive"
    config:
      encrypt: true
