[package]
name = "exploit_framework"
version = "2.0.0"
edition = "2021"

[dependencies]
# Memory manipulation and assembly
goblin = "0.7"
capstone = "0.11"
# keystone-engine = "0.1"  # Temporarily disabled - build issues
unicorn-engine = "2.0"
memmap2 = "0.9"

# Networking
tokio = { version = "1.35", features = ["full"] }
bytes = "1.5"

# Random generation
rand = "0.8"

# Binary analysis
object = "0.32"
gimli = "0.28"
addr2line = "0.21"

# Utilities
hex = "0.4"
colored = "2.1"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"

# Fuzzing support
afl = "0.15"
honggfuzz = "0.5"

# Crypto for payload encoding
aes = "0.8"
base64 = "0.21"
sha2 = "0.10"

[[bin]]
name = "exploit-framework"
path = "src/main.rs"
